# For more info see: https://github.com/apify/pull-request-toolkit-action/
name: Apify pull request toolkit

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'labeled', 'unlabeled', 'edited', 'ready_for_review'] # The first 3 are default.

concurrency: # This is to make sure that it's executed only for the most recent changes of PR.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  apify-pr-toolkit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: run pull-request-toolkit action
        uses: apify/pull-request-toolkit-action@main
        with:
          repo-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_GITHUB_TOKEN }}
          org-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_GITHUB_TOKEN }}
          zenhub-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_ZENHUB_TOKEN }}
