inputs:
  package_name:
    required: true
    type: string
  version_number:
    required: true
    type: string
  is_prerelease:
    required: true
    type: string
  ref:
    required: true
    type: string
  python_version:
    required: false
    type: string
    default: "3.13" # The newest Python version.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python_version }}

    - name: Set up uv package manager
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      run: make install-dev

    # Updates the version number in the project's configuration.
    - name: Set version in pyproject.toml
      shell: bash
      run: |
        if [ -n "${{ inputs.is_prerelease }}" ]; then
          next_beta=$(
            curl "https://pypi.org/pypi/${{ inputs.package_name }}/json" | jq --raw-output '
              [
                .releases |
                  keys |
                  .[] |
                  select(startswith("${{ inputs.version_number }}b")) |
                  split("b") |
                  .[1] |
                  tonumber
              ] |
              sort_by(- .) |
              .[0] + 1
            '
          )
          new_version="${{ inputs.version_number }}b${next_beta}"
          echo "Updating version in pyproject.toml to ${new_version}"
          uv version "${new_version}"
        fi

    # Builds the package.
    - name: Build package
      shell: bash
      run: make build
