name: lint github workflows

on:
  workflow_call:
    inputs:
      extraArgs:
        description: Additional extra arguments for actionlint
        required: false
        type: string

env:
  # renovate: datasource=docker depName=rhysd/actionlint
  ACTIONLINT_VERSION: 1.7.12

jobs:
  lint:
    runs-on: ubuntu-22.04-arm64
    steps:
      - name: clone repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: lint
        run: |
          # Disabling shellcheck as we are not using it
          docker run \
            -v $(pwd):/repo \
            --workdir /repo \
            --rm \
            rhysd/actionlint:${{ env.ACTIONLINT_VERSION }} \
            -shellcheck="" ${{ inputs.extraArgs }}
