name: lint workflows

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  lint:
    uses: ./.github/workflows/lint_gh_actions.yaml
    with:
      extraArgs: -ignore 'property "aws_.+" is not defined in .+'
