name: lint workflows

on:
  workflow_dispatch:

  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  lint:
    uses: ./.github/workflows/lint_gh_actions.yaml
    with:
      extraArgs: >
        -ignore 'label "ubuntu-22.04-arm64" is unknown. .+'
        -ignore 'property "aws_.+" is not defined in .+'
